#!/bin/sh -e

vcs 'AES128_tb' '-full64' '-timescale=1ns/1ps' '-debug_all' '-sdf' 'max:AES128_tb/DUT:/users/students/r0622838/digital-design-flow-aes/02_SYNTHESIS/data/AES128.synthesis.sdf' '-negdelay' '+neg_tchk' "-lca" "-makedepends=Makefile.VCSMX_FOR_DVE_REBUILD"
gmake -f Makefile.VCSMX_FOR_DVE_REBUILD
vcs 'AES128_tb' '-full64' '-timescale=1ns/1ps' '-debug_all' '-sdf' 'max:AES128_tb/DUT:/users/students/r0622838/digital-design-flow-aes/02_SYNTHESIS/data/AES128.synthesis.sdf' '-negdelay' '+neg_tchk'
