# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcvu440-flga2892-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /users/students/r0622838/digital-design-flow-aes/AES128-vivado/AES128-vivado.cache/wt [current_project]
set_property parent.project_path /users/students/r0622838/digital-design-flow-aes/AES128-vivado/AES128-vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /users/students/r0622838/digital-design-flow-aes/AES128-vivado/AES128-vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /users/students/r0622838/digital-design-flow-aes/99_SRC/my_src_hdl/AddRoundKey.vhd
  /users/students/r0622838/digital-design-flow-aes/99_SRC/my_src_hdl/Control_FSM.vhd
  /users/students/r0622838/digital-design-flow-aes/99_SRC/my_src_hdl/Keyscheduler.vhd
  /users/students/r0622838/digital-design-flow-aes/99_SRC/my_src_hdl/PKG_AES128.vhd
  /users/students/r0622838/digital-design-flow-aes/99_SRC/my_src_hdl/SubBytes.vhd
  /users/students/r0622838/digital-design-flow-aes/99_SRC/my_src_hdl/bytesub.vhd
  /users/students/r0622838/digital-design-flow-aes/99_SRC/my_src_hdl/mixcolumn.vhd
  /users/students/r0622838/digital-design-flow-aes/99_SRC/my_src_hdl/shiftrow.vhd
  /users/students/r0622838/digital-design-flow-aes/99_SRC/my_src_hdl/AES128.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top AES128 -part xcvu440-flga2892-3-e


write_checkpoint -force -noxdef AES128.dcp

catch { report_utilization -file AES128_utilization_synth.rpt -pb AES128_utilization_synth.pb }
